#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 03, 2022 04:45:18 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import CardList

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = CardList.CardList(_top1)
    root.mainloop()

def addButtonClicked(*args):
    print('CardList_support.addButtonClicked')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def buttonDisplayCardClicked(*args):
    print('CardList_support.buttonDisplayCardClicked')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def listItemDoubleClick(*args):
    print('CardList_support.listItemDoubleClick')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    CardList.start_up()




